


#define TEXTURE_ID_MAX_COUNT  ( 1024 )
enum TEXTURE_ID {
    TextureID_DefaultTexture,
    TextureID_WhiteTexture,
    
    TextureID_EntitySpawn_Indicator,
    TextureID_Worm_Body,
    TextureID_Barrel,
    TextureID_Barrel_Rot90,
    TextureID_Barrel_End,
    TextureID_Collector,
    TextureID_Collector_Flash,
    TextureID_PlayerBullet_Head,
    TextureID_PlayerBullet_Tail,
    TextureID_MinerLaser_Body,
    TextureID_MinerLaser_End,
    TextureID_Circle,
    TextureID_HalfCircle,
    TextureID_RoundedDome,
    TextureID_Dome,
    TextureID_HalfDome,
    TextureID_Glow,
    TextureID_Powerup_Body,
    TextureID_Powerup_Health,
    TextureID_Powerup_Shield,
    TextureID_ScoreMultiplier,
    TextureID_AutoTurret,
    TextureID_AutoTurretLaser_Body,
    TextureID_AutoTurretLaser_End,
    TextureID_BayDoors_Interior,
    TextureID_BayDoors_SpawnDest,
    TextureID_ZeroPoint_Base_Inactive,
    TextureID_ZeroPoint_Base_Active,
    TextureID_Looper,
    TextureID_Blimp,
    TextureID_SatelliteDish,
    TextureID_SatelliteDish_Shield,
    TextureID_SatelliteDish_ShieldHit,
    TextureID_Asteroid00,
    TextureID_Asteroid01,
    TextureID_Asteroid02,
    TextureID_Asteroid03,
    TextureID_Asteroid04,
    TextureID_Asteroid05,
    TextureID_Asteroid06,
    TextureID_Asteroid07,
    TextureID_Turret_InsideBarrel,
    TextureID_Turret_Base,
    TextureID_Turret_Shield_Glow,
    TextureID_Turret_Shield_Ring,
    TextureID_Recon,
    TextureID_EnemyBullet_Core,
    TextureID_EnemyBullet_Surface,
    TextureID_TractorBeam_Glow,
    TextureID_TractorBeam_Ring,
    TextureID_MegaMiner_Body,
    TextureID_Worm_Tag,
    TextureID_Worm_TagChain,
    TextureID_Loader_Body,
    TextureID_Spitter_Base,
    TextureID_Spit,
    TextureID_ObservationDeck,
    TextureID_ObservationDeck_Shield_Inner,
    TextureID_ObservationDeck_Shield_RingAndGlow,
    TextureID_ObservationDeck_Barrier,
    TextureID_ObservationDeck_Window,
    TextureID_SecurityDrone_Turret_End,
    TextureID_Gunner_Barrel,
    TextureID_MissileLauncher_Barrel,
    TextureID_MissileLauncher_Barrel_BackEnd,
    TextureID_MissileLauncher_Barrel_FrontEnd,
    TextureID_MissileLauncher_Health,
    TextureID_HowToPlay_Mouse,
    
    TextureID_Background_01,
    
    TextureID_Item_None,
    TextureID_Item_Blaster,
    TextureID_Item_GrappleBeam,
    TextureID_Item_TractorBeam,
    TextureID_Item_GravityWell,
    TextureID_Item_Shield,
    TextureID_Item_Collector,
    
    TextureID_ObservationDeck_Icon,
    TextureID_Cow,
    TextureID_Spacesuit,
    TextureID_Player_Avatar,
    TextureID_Icon_LevelComplete,
    
    TextureID_Font,
    
    TextureID_Font_0_75,
    TextureID_Font_0_90,
    TextureID_Font_1_00,
    TextureID_Font_1_25,
    TextureID_Font_1_35,
    TextureID_Font_1_50,
    TextureID_Font_1_75,
    TextureID_Font_2_00,
    TextureID_Font_2_25,
    TextureID_Font_2_50,
    TextureID_Font_2_75,
    TextureID_Font_3_00,
    TextureID_Font_7_00,
    
    TextureID_Font_Title_1_00,
    TextureID_Font_Title_2_00,
    TextureID_Font_Title_2_50,
    TextureID_Font_Title_3_00,
    TextureID_Font_Title_3_50,
    TextureID_Font_Title_4_00,
    TextureID_Font_Title_14_00,
    
    TextureID_WaveEditorBackground_AutoTurret,
    TextureID_WaveEditorBackground_Asteroid,
    TextureID_WaveEditorBackground_Turret,
    TextureID_WaveEditorBackground_BombLauncher,
    TextureID_WaveEditorBackground_Worm,
    TextureID_WaveEditorBackground_Spitter,
    
    TextureID_Wave_Bitmap,
    TextureID_Wave_Bitmap_End = TextureID_Wave_Bitmap + TEXTURE_ID_MAX_COUNT,
    
    TextureID_Count,
};

enum MODEL_ID {
    MeshID_Line,
    MeshID_Rect,
    MeshID_RectOutline,
    MeshID_Circle,
    MeshID_CircleOutline,
    MeshID_Triangle,
    MeshID_Triangle_FlipUV,
    MeshID_TriangleOutline,
    //MeshID_Hexagon,
    //MeshID_Octagon,
    
    MeshID_ObservationDeck_Barrier,
    MeshID_ObservationDeck_Icon,
    MeshID_BlimpA,
    MeshID_BlimpB,
    MeshID_BlimpC,
    MeshID_Turret_Shield_EndCap,
    MeshID_Cow,
    MeshID_Spacesuit,
    
    MeshID_Count,
};

enum LEVEL_ID {
    LevelID_Market,
    LevelID_Blimp,
    LevelID_Turret,
    LevelID_TurretShield,
    LevelID_BombLauncher,
    LevelID_AutoTurret,
    LevelID_PlayerShield,
    LevelID_MegaMiner,
    LevelID_GravityWell,
    LevelID_Worm,
    LevelID_Collector,
    LevelID_ObservationDeck,
    
    LevelID_Count,
};

enum AUDIO_ID {
    AudioID_Null,
    
    AudioID_Music_TitleScreen_Intro,
    AudioID_Music_TitleScreen_Loop,
    AudioID_Music_Level_Track01_Intro,
    AudioID_Music_Level_Track01_Loop,
    AudioID_Music_Level_Track03_Intro,
    AudioID_Music_Level_Track03_Loop,
    AudioID_Music_Level_Track04_Intro,
    AudioID_Music_Level_Track04_Loop,
    
    AudioID_Music_End,
    
    AudioID_SpitBonus_Red,
    AudioID_SpitBonus_Yellow,
    AudioID_SpitBonus_Blue,
    
    AudioID_Button_Yes,
    AudioID_Button_No,
    
    AudioID_Bullet_Slow,
    AudioID_Bullet_Fast,
    
    AudioID_Asteroid_Collide_Large_01,
    AudioID_Asteroid_Collide_Large_02,
    AudioID_Asteroid_Collide_Small_01,
    AudioID_Asteroid_Collide_Small_02,
    
    AudioID_Miner_Laser,
    
    AudioID_Entity_Spawn,
    AudioID_Entity_Death_Large,
    AudioID_Entity_Death_Medium,
    AudioID_Entity_Death_Small,
    AudioID_Entity_Death_Tiny,
    AudioID_Worm_Death_Large,
    AudioID_Worm_Death_Small,
    
    AudioID_Powerup,
    
    AudioID_EnemyBullet_01,
    AudioID_EnemyBullet_02,
    AudioID_Fireball_01,
    AudioID_Fireball_02,
    
    AudioID_Player_Damage,
    AudioID_Player_SecondaryDamage,
    
    AudioID_ScoreMultiplier,
    
    AudioID_Count,
};

